<?php

$labels = array();
$labels['yubikey'] = 'OTP';
$labels['yubikeyrequired'] = 'OTP YubiKey requis';
$labels['yubikeyid'] = 'Identifiant YubiKey';
$labels['yubikeyid2'] = 'Identifiant YubiKey 2';
$labels['yubikeyid3'] = 'Identifiant YubiKey 3';
$labels['yubikeysettings'] = 'Authentification YubiKey';

$messages = array();
$messages['yubikeyauthfailed'] = $labels['yubikey'].' a &eacute;chou&eacute;';

?>



